FROM alpine:3.20

WORKDIR /app

#Add comments to commit and show in web version the updates


#adding more comments!


#comments



COPY target/*.jar app.jar

CMD ["sh","-c","echo 'Deployed artifact inside container:' && ls -l /app/app.jar"]